# Generated by Django 5.1.3 on 2024-11-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeSong",
            fields=[
                (
                    "song_name",
                    models.CharField(
                        db_column="歌曲名稱",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "work_name",
                    models.CharField(db_column="作品名稱", max_length=45, null=True),
                ),
                (
                    "season_or_other",
                    models.CharField(db_column="季度或其他", max_length=45, null=True),
                ),
                (
                    "broadcast_year",
                    models.IntegerField(db_column="播出年份", null=True),
                ),
                (
                    "broadcast_month",
                    models.IntegerField(db_column="播出月份", null=True),
                ),
                (
                    "singer_or_group",
                    models.CharField(
                        db_column="歌手或者其他團體", max_length=45, null=True
                    ),
                ),
            ],
            options={
                "db_table": "anime_song",
            },
        ),
    ]
