# Generated by Django 5.1.3 on 2024-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_anime_song", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animesong",
            name="singer_or_group",
            field=models.CharField(
                db_column="歌手或者表演團體", max_length=45, null=True
            ),
        ),
    ]
