# Generated by Django 5.1.3 on 2024-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_anime_song", "0002_alter_animesong_singer_or_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="animesong",
            name="song_url",
            field=models.CharField(db_column="音樂網址", max_length=100, null=True),
        ),
    ]
